name: Deploy to GCP
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GCP by using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          if [ ! -d "/home/ihsanulz92/app" ]
          then
            git clone git@github.com:Ihsan-null/gcp-deployment.git /home/ihsanulz92/app
          fi
          cd /home/ihsanulz92/app
          git pull origin master
          docker stop myApp
          docker rm myApp
          cd program
          docker build -t my-app:latest .
          docker run -d -e "HTTP_PORT=:80" -e "CONNECTION_STRING=root:12345@tcp(35.240.215.27:3306)/alta_db?charset=utf8mb4&parseTime=True&loc=Local" -p 80:80 --name myApp my-app:latest